### ISSUE TITLE
Consider changing app display name

### ISSUE THREAD

**Issue by vangyyy** [forem/DEV-Android#93] opened 2020-07-20 13:58 UTC
Name of the app is currently set to **DEV Community**. This name is too long and is often shortened by launchers to **DEV Com...** as shown in the attached screenshot (Im using Pixel launcher on Google Pixel 3 XL). This looks quite bad and is also not very descriptive in it's shortened form.

![screenshot](https://i.imgur.com/AyuuTRG.jpg)

I would suggest using **dev.to** since the app is basically just a webview. **DEV.to** or **Dev.to** may ale be good options.

**Comment by fdoxyz** [comment] 2020-07-27 15:00
Thank you for flagging this @vangyyy! We'll definitely consider these suggestions to improve the way the app is displayed

**Comment by alokbharti** [comment] 2020-10-04 05:34
Hey @vangyyy , @fdoxyz , can I take this issue?

**Comment by vangyyy** [comment] 2020-10-04 11:48
Sure I would like to see it done, but it's not on me to decide if it's accepted. Maybe create a pull request and discussion will start on this, as it seems to be stale at the moment.

**Comment by PrajjwalDatir** [comment] 2020-12-28 05:55
@vangyyy  I have created a PR. Do tell me , if you want me to do anything more :)

**Comment by fdoxyz** [comment] 2021-01-04 15:31
Thank you for the contribution @PrajjwalDatir. The issue is marked as discussion so no official stance has been made yet on whether we will actually change the app name.

In this new year we may see some bigger changes come to the project similar to how we've been experimenting on iOS with https://github.com/forem/ForemWebView-ios

Thank you for your interest and I can recommend you (and anyone interested) to keep an eye on the project in the coming weeks :)

**Comment by PrajjwalDatir** [comment] 2021-10-02 18:26
@fdoxyz It's been 9 months (ᵔᴥᵔ)

**Closed** 2022-05-22 13:32 UTC
Labels: optimization, discussion, accessibility
