### ISSUE TITLE
App always crashes when accessing from the notification area

### ISSUE THREAD

**Issue by patarapolw** [forem/DEV-Android#95] opened 2020-08-10 10:25 UTC
For about a week now, dev.to Android app always crashes when accessed from push message, i.e. Notification Area, on Vivo.

Actually, the first ever notification message is [Wisdom engine "DEV Community" runtime exception](https://dev.to/patarapolw/wisdom-engine-dev-community-runtime-exception-2ahh). After I slided to hide that message, this error consistently happen.

**To Reproduce**

1. A notification message is received.
2. Click on the notification message
3. App opens and dies without any visible UI or message
4. However, app can still be accessed via clicking the icon. (And the notification count is still there.)

**Expected behavior**

No crashes.

**Smartphone (please complete the following information):**
 - Device: vivo1910
 - OS: Android version 10 / vivo ROM Funtouch OS_10
 - Version: 1.4.1

**Comment by maestromac** [comment] 2020-08-10 14:08
Hello @patarapolw can you try clearing the app's cache and storage and see if you can still reproduce this issue?

**Comment by patarapolw** [comment] 2020-08-10 14:13
Now, it's even worse. It crashes upon trying to sign in both via GitHub and Twitter.

**Comment by fdoxyz** [comment] 2020-08-10 15:06
Thank you for the report @patarapolw! I'm now seeing this problem too on Android 8. After clearing my data I didn't see the expected result when tapping on a PN either, but I didn't encounter the login problem you mention.

AFAIK it's not straightforward to debug the release build from the store. A viable way to debug this is to boot up a local forem install with Push Notifications configured (you'll need a free [Pusher Beams & Firebase](https://docs.forem.com/backend/pusher/#mobile-push-notifications) account) in order to test with a debug version of the app, which requires some setup to get everything running properly.

We have a few issues I'm hoping to sort out soon and this is an important one.

**Comment by bluetoothfx** [comment] 2020-11-22 16:08
@fdoxyz would you please share how should I setup complete local development environment for this issue. I guess I need to generate notification from Web app. Please guide me how should I make an environment which I can debug with.
BTW I have windows based development environment + I would like to go with Docker if there is any. Thanks.

**Comment by fdoxyz** [comment] 2020-11-23 14:03
Absolutely @bluetoothfx! Here's the steps with a few links for step-by-step guides:

1. Spin up the local web app. This is the guide for the container installation: https://docs.forem.com/installation/containers/
1. Since you'll be working on your device I can recommend using [ngrok](https://ngrok.com/) to easily expose your local app
1. The Push Notifications are sent using Pusher Beams. This is the step by step installation setup for that (you'll only need to setup for Android): https://docs.forem.com/backend/pusher/#mobile-push-notifications
1. You'll want to put the `google-services.json` file in the `app` directory of the Android project and update both `gradle.properties` and `CustomWebViewClient` (add to overrideUrlList) with your custom URL

Let me know if you have any issues along the way :)

**Comment by sami1236751** [comment] 2021-04-26 05:22
I have an app crashing problem, many of app are crashing my phone what can i fo this?

**Comment by sami1236751** [comment] 2021-04-26 05:26
all important app are crashed my phone i think vivo is a very unfit phone.

**Comment by archanamm95** [comment] 2021-11-30 08:20
Am using iqoo phone .Now when ever I open whatspp it will automatically close and back to home page

**Comment by bluetoothfx** [comment] 2021-11-30 08:27
> Am using iqoo phone .Now when ever I open whatspp it will automatically close and back to home page

Could you please attach your finds? e.g video. Thanks

**Comment by bluetoothfx** [comment] 2021-11-30 08:30
> Absolutely @bluetoothfx! Here's the steps with a few links for step-by-step guides:
> 
> 1. Spin up the local web app. This is the guide for the container installation: https://docs.forem.com/installation/containers/
> 2. Since you'll be working on your device I can recommend using [ngrok](https://ngrok.com/) to easily expose your local app
> 3. The Push Notifications are sent using Pusher Beams. This is the step by step installation setup for that (you'll only need to setup for Android): https://docs.forem.com/backend/pusher/#mobile-push-notifications
> 4. You'll want to put the `google-services.json` file in the `app` directory of the Android project and update both `gradle.properties` and `CustomWebViewClient` (add to overrideUrlList) with your custom URL
> 
> Let me know if you have any issues along the way :)

Dear @fdoxyz it has been a year but I didn't manage schedule for set the environment to reproduce the issue. I am sorry from my heart. If anyone interested or team want to take action to solve please go ahead.

**Comment by fdoxyz** [comment] 2021-12-07 22:13
No worries @bluetoothfx, thank you for taking the time to look into it in the first place.

We are planning to sunset the DEV Android app ([just like we did for iOS](https://dev.to/devteam/sunsetting-the-devto-ios-app-44nl)) soon (see #138) so it feels like fixing this bug won't be needed in the end.

If you or anyone following this thread would like to receive private beta access feel free to share your DEV username and we'll reach out for this.

Thank you everyone for being a part of this project and I hope the same level of collaboration we've seen here gets translated to the Forem apps as soon as we're able to open source them ❤️

**Comment by rt4914** [comment] 2022-09-20 20:43
Closing this as it is not required now.

**Closed by rt4914** 2022-09-20 20:43 UTC
Labels: bug, status: approved
